### ISSUE TITLE
Props to translate buttons and style

### ISSUE THREAD

**Issue by basequatro** [marcelglaeser/react-native-help-bubbles#1]
Props to translate buttons and style

**Comment by marcelglaeser** [comment]
Same props:
showStepNum = show step numbers or not
customToolTipStyle = styles for the tooltip
customArrowStyle = styles for the small arrow
stopBtnTitle = title for the stop button
nextBtnTitle = title for the next button
prevBtnTitle = title for the prev button

**Comment by basequatro** [comment]
Submitted PR with those props.
Thanks
